### PR TITLE
Add user option to use JPMS

### PR DESCRIPTION
**Pull request by Adito5393**
Following up on issue #1. Here is a working concept of how the archetype would handle the module-info.

TODO:
- [x] write the `archetype-post-generate.groovy` [file](https://maven.apache.org/archetype/maven-archetype-plugin/advanced-usage.html) to delete the `module-info.java` if the user property `useJavaPlatformModuleSystem=false` - the pom.xml does not need to be changed;
- [ ] update README.md with how the new parameters (`useJavaPlatformModuleSystem`, `run.with.java.module` and `target.run.module.class`) work;

The current PR is a working JPMS project, so feel free to test it and provide feedback!

### CODE REVIEW

**Comment by Adito5393** [comment]
The project is completed for testing with module-info and without (making use of `useJavaPlatformModuleSystem` project parameter)! 

Will this PR be considered for merging? If not, I will not invest time in updating the docs.

**Comment by lburaggi** [comment]
Good job

**Review by lburaggi — COMMENTED** [review]
Accepted

**Comment by FDelporte** [comment]
@Adito5393 thanks for your contribution!!! 

Regarding the documentation: this Maven Archetype is also described on https://pi4j.com/getting-started/developing-on-a-remote-pc/. Please, where applicable, update both the README in this repository and the website page on https://github.com/Pi4J/pi4j.github.io/blob/main/content/getting-started/developing-on-a-remote-pc.md.

**Pull request merged**
